'use strict'

// --- Narrator
// Omnipresent voice
// --- Character A
// Sanguine: curious, outgoing, sincere, optimistic, enthusiastic
// --- Character B
// Melancholic: pessimistic, nostalgic, analytical
// --- Character C
// Choleric: flippant, hedonistic, assertive

const vocabulary = {
  a: {
    nouns: [
      'he',
      'she',
      'it',
      'the guest',
      'the man',
      'nobody',
      'everyone',
      'the woman',
      'the girl',
      'the boy',
      'the child',
      'the employee',
      'the manager',
      'the block',
      'the chain',
      'the dog',
      'the door',
      'the warehouse',
      'Helen',
      'The Prius',
      'Ahmed',
      'Lorenzo',
      'Eliza',
      'the Lawgiver',
      'Hanoi'
    ],
    adjectives: [
      'warm',
      'good',
      'close',
      'closed',
      'next',
      'different',
      'early',
      'content',
      'valuable',
      'brilliant',
      'new',
      'safe',
      'crazy',
      'happy',
      'important',
      'right',
      'alright',
      'relieved',
      'good',
      'curious',
      'vibrant',
      'colorful',
      'melodic',
      'harmonious',
      'friendly'
    ],
    verbs: [
      'will be',
      'has been',
      'is',
      'is not',
      'would be',
      'was',
      'was not',
      'seemed',
      'might be'
    ],
    actions: [
      'heard',
      'overheard',
      'saw',
      'visited',
      'revisited',
      'looked at',
      'knew',
      'needed',
      'was aware of',
      'longed for',
      'travelled to',
      'found',
      'touched',
      'told about',
      'wanted',
      'indicated',
      'laughed',
      'embraced',
      'sang',
      'yelled'
    ],
    futures: ['will go', 'will return', 'will know', 'will be there', 'will come here'],
    presents: ['saw', 'talks to', 'looks at', 'go to', 'get to know'],
    objects: [
      'them',
      'her',
      'him',
      'the location',
      'the area',
      'it',
      'something',
      'what happened',
      'the object',
      'the thing',
      'the individual',
      'the situation',
      'the process',
      'the story',
      'the screen',
      'the organization',
      'the group',
      'the border',
      'the building',
      'the source',
      'the company',
      'the club',
      'the assembly',
      'the position',
      'someone',
      'black-box',
      'the protocol',
      'the warehouse',
      'the complex',
      'the guard',
      'the hairdresser',
      'the river',
      'the prop',
      'the topography',
      'the space',
      'the weather',
      'the climate',
      'the zone'
    ],
    statements: ['yes!', 'yes', 'yes', 'I know', 'true'],
    questions: ['yes?', 'no?', 'really?', 'why not?', 'how?', 'where?', 'now?', 'why?', 'what?'],
    punctations: ['', '', '', '...', '.'],
    adverbs: [
      'quickly',
      'suddenly',
      'finally',
      'always',
      'really',
      'meaningfully',
      'hilariously',
      'socially'
    ],
    sentenceTemplates: [
      '{{ statement}}, {{ noun }} {{ verb }} {{ adjective }}',
      '{{ statement}}... {{ noun }} {{ verb }} {{ adjective }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}',
      'I {{ action }} {{ object }}{{ punctation }}',
      'I was {{ adjective }}{{ punctation }}',
      'You were {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ adverb }} {{ action }} {{ object }}',
      '{{ statement }}{{ punctation }}',
      '{{ question }}',
      '{{ question }} {{ noun }} {{ action }} {{ object }}?',
      '{{ noun }} {{ verb }} {{ adjective }}?',
      'if {{ noun }} {{ present }} {{ object }}, {{ noun }} {{ future }} {{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}'
    ]
  },
  b: {
    nouns: [
      'he',
      'she',
      'it',
      'the guest',
      'the man',
      'nobody',
      'everyone',
      'the woman',
      'the girl',
      'the boy',
      'the child',
      'the employee',
      'the manager',
      'the block',
      'the chain',
      'the dog',
      'the door',
      'the warehouse',
      'Helen',
      'The Prius',
      'Ahmed',
      'Lorenzo',
      'Eliza',
      'Antwerp',
      'Lagos',
      'the Lawgiver',
      'Hanoi'
    ],
    adjectives: [
      'cold',
      'distant',
      'absent',
      'closed',
      'far away',
      'next',
      'indifferent',
      'shaken',
      'trapped',
      'angry',
      'nervous',
      'late',
      'tired',
      'blocked',
      'crazy',
      'hurt',
      'old',
      'uneasy',
      'leaving',
      'deep',
      'sad',
      'important',
      'relieved',
      'impossible',
      'wrong',
      'bad',
      'uneasy',
      'detailed',
      'exasperated',
      'hardened',
      'solitary',
      'communist'
    ],
    verbs: [
      'will be',
      'has been',
      'is',
      'is not',
      'would be',
      'was',
      'was not',
      'seemed',
      'might be'
    ],
    actions: [
      'heard',
      'overheard',
      'saw',
      'visited',
      'revisited',
      'looked at',
      'stared at',
      'knew',
      'needed',
      'was aware of',
      'mentioned',
      'longed for',
      'travelled to',
      'found',
      'struggled with',
      'touched',
      'thought about',
      'dreamt about',
      'told about',
      'wanted',
      'indicated',
      'analysed',
      'felt',
      'sat in silence',
      'regressed',
      'thought back',
      'imagined',
      'cried',
      'sobbed'
    ],
    futures: [
      'will go',
      'will return',
      'will know',
      'will be there',
      'will come here',
      'will communicate',
      'will try',
      'will attack'
    ],
    presents: ['saw', 'talks to', 'looks at', 'go to', 'get to know'],
    objects: [
      'them',
      'her',
      'him',
      'the location',
      'the area',
      'it',
      'something',
      'what happened',
      'the object',
      'the thing',
      'the individual',
      'the situation',
      'the process',
      'the story',
      'the screen',
      'the organization',
      'the group',
      'the border',
      'the building',
      'the source',
      'the company',
      'the club',
      'the assembly',
      'the position',
      'someone',
      'black-box',
      'the protocol',
      'the warehouse',
      'the complex',
      'the guard',
      'the hairdresser',
      'the river',
      'the prop',
      'the topography',
      'the space',
      'the weather',
      'the climate',
      'the zone'
    ],
    singleObjects: [
      'story',
      'step',
      'mechanism',
      'device',
      'vehicle',
      'engine',
      'rule',
      'border',
      'process',
      'organization',
      'machine'
    ],
    statements: [
      'yes',
      'yes',
      'yes',
      'no',
      'no',
      'no',
      'maybe',
      'perhaps',
      'could be',
      'I know',
      'I have no idea',
      'I had no idea',
      'I dont know',
      'no idea',
      'true',
      'false',
      'sure',
      'Im sorry',
      'Sorry',
      'I apologize'
    ],
    questions: ['yes?', 'no?', 'really?', 'why not?', 'how?', 'where?', 'now?', 'why?', 'what?'],
    punctations: ['', '', '', '...', '.'],
    adverbs: [
      'quickly',
      'suddenly',
      'finally',
      'always',
      'never',
      'rarely',
      'really',
      'slowly',
      'carefully',
      'nostalgically',
      'sorrowfully',
      'delicately',
      'scornfully'
    ],
    sentenceTemplates: [
      '{{ statement}}, {{ noun }} {{ verb }} {{ adjective }}',
      '{{ statement}}... {{ noun }} {{ verb }} {{ adjective }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}',
      'I {{ action }} {{ object }}{{ punctation }}',
      'I was {{ adjective }}{{ punctation }}',
      'You were {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ adverb }} {{ action }} {{ object }}',
      '{{ statement }}{{ punctation }}',
      '{{ question }}',
      '{{ question }} {{ noun }} {{ action }} {{ object }}?',
      '{{ noun }} {{ verb }} {{ adjective }}?',
      'if {{ noun }} {{ present }} {{ object }}, {{ noun }} {{ future }} {{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}'
    ]
  },
  c: {
    nouns: [
      'he',
      'she',
      'it',
      'the guest',
      'the man',
      'nobody',
      'everyone',
      'the woman',
      'the girl',
      'the boy',
      'the child',
      'the employee',
      'the manager',
      'the block',
      'the chain',
      'the dog',
      'the door',
      'the warehouse',
      'Helen',
      'The Prius',
      'Ahmed',
      'Lorenzo',
      'Eliza',
      'Antwerp',
      'Lagos',
      'the Lawgiver',
      'Hanoi',
      'the objective'
    ],
    adjectives: [
      'next',
      'different',
      'early',
      'angry',
      'late',
      'valuable',
      'new',
      'crazy',
      'old',
      'important',
      'right',
      'wrong',
      'bad',
      'open',
      'late',
      'communist',
      'futuristic',
      'furious',
      'insistent',
      'radicalized',
      'serious',
      'serious',
      'angered'
    ],
    verbs: [
      'will be',
      'has been',
      'is',
      'is not',
      'would be',
      'was',
      'was not',
      'seemed',
      'might be'
    ],
    actions: [
      'heard',
      'saw',
      'visited',
      'looked at',
      'stared at',
      'knew',
      'needed',
      'mentioned',
      'travelled to',
      'found',
      'wanted',
      'indicated',
      'showed',
      'demonstrated',
      'attacked',
      'directed',
      'eliminated',
      'reduced',
      'ignited',
      'initiated',
      'dragged',
      'stabbed',
      'enhanced',
      'yelled',
      'fought',
      'plead'
    ],
    futures: [
      'will go',
      'will return',
      'will know',
      'will be there',
      'will come here',
      'will communicate',
      'will run',
      'will see',
      'will pass',
      'will enable',
      'will strike',
      'will dominate'
    ],
    presents: ['saw', 'talks to', 'looks at', 'go to', 'get to know'],
    objects: [
      'them',
      'her',
      'him',
      'the location',
      'the area',
      'it',
      'something',
      'what happened',
      'the object',
      'the thing',
      'the individual',
      'the situation',
      'the process',
      'the story',
      'the screen',
      'the organization',
      'the group',
      'the border',
      'the building',
      'the source',
      'the company',
      'the club',
      'the assembly',
      'the position',
      'someone',
      'black-box',
      'the protocol',
      'the warehouse',
      'the complex',
      'the guard',
      'the hairdresser',
      'the river',
      'the prop',
      'the topography',
      'the space',
      'the weather',
      'the climate',
      'the zone'
    ],
    singleObjects: [
      'story',
      'step',
      'mechanism',
      'device',
      'vehicle',
      'engine',
      'rule',
      'border',
      'process',
      'organization',
      'machine'
    ],
    statements: [
      'yes',
      'yes',
      'yes',
      'no',
      'no',
      'no',
      'maybe',
      'perhaps',
      'could be',
      'I know',
      'I have no idea',
      'I had no idea',
      'I dont know',
      'no idea',
      'true',
      'false',
      'sure'
    ],
    questions: ['yes?', 'no?', 'really?', 'why not?', 'how?', 'where?', 'now?', 'why?', 'what?'],
    punctations: ['', '', '', '...', '.'],
    adverbs: [
      'quickly',
      'suddenly',
      'finally',
      'always',
      'never',
      'rarely',
      'really',
      'slowly',
      'carefully'
    ],
    sentenceTemplates: [
      '{{ statement}}, {{ noun }} {{ verb }} {{ adjective }}',
      '{{ statement}}... {{ noun }} {{ verb }} {{ adjective }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}',
      'I {{ action }} {{ object }}{{ punctation }}',
      'I was {{ adjective }}{{ punctation }}',
      'You were {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ adverb }} {{ action }} {{ object }}',
      '{{ statement }}{{ punctation }}',
      '{{ question }}',
      '{{ question }} {{ noun }} {{ action }} {{ object }}?',
      '{{ noun }} {{ verb }} {{ adjective }}?',
      'if {{ noun }} {{ present }} {{ object }}, {{ noun }} {{ future }} {{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}'
    ]
  },
  narrator: {
    nouns: [
      'he',
      'she',
      'it',
      'the guest',
      'the man',
      'nobody',
      'everyone',
      'the woman',
      'the girl',
      'the boy',
      'the child',
      'the employee',
      'the manager',
      'the block',
      'the chain',
      'the dog',
      'the door',
      'the warehouse',
      'Helen',
      'The Prius',
      'Ahmed',
      'Lorenzo',
      'Eliza',
      'Antwerp',
      'Lagos',
      'the Lawgiver',
      'Hanoi'
    ],
    adjectives: [
      'cold',
      'warm',
      'good',
      'distant',
      'absent',
      'close',
      'closed',
      'far away',
      'next',
      'different',
      'indifferent',
      'early',
      'shaken',
      'content',
      'trapped',
      'angry',
      'nervous',
      'late',
      'valuable',
      'brilliant',
      'tired',
      'blocked',
      'new',
      'safe',
      'hurt',
      'old',
      'uneasy',
      'happy',
      'leaving',
      'important',
      'right',
      'alright',
      'relieved',
      'impossible',
      'wrong',
      'bad',
      'good',
      'open',
      'present',
      'past',
      'future',
      'variant',
      'prime',
      'upper percentile',
      'sub-prime',
      'ancient',
      'populist',
      'exceptional',
      'substantial',
      'unnerving',
      'reticent',
      'sealed',
      'late',
      'communist'
    ],
    verbs: [
      'will be',
      'has been',
      'is',
      'is not',
      'would be',
      'was',
      'was not',
      'seemed',
      'might be'
    ],
    actions: [
      'heard',
      'overheard',
      'saw',
      'visited',
      'revisited',
      'looked at',
      'stared at',
      'knew',
      'needed',
      'was aware of',
      'mentioned',
      'longed for',
      'travelled to',
      'found',
      'struggled with',
      'touched',
      'thought about',
      'dreamt about',
      'told about',
      'wanted',
      'indicated',
      'showed',
      'demonstrated',
      'attacked',
      'critiqued',
      'directed',
      'eliminated',
      'subverted',
      'reduced',
      'ignited',
      'initiated',
      'altered',
      'intuited',
      'dragged',
      'danced',
      'jumped',
      'stabbed',
      'supported',
      'upheld',
      'vindicated',
      'enhanced',
      'said'
    ],
    futures: [
      'will go',
      'will return',
      'will know',
      'will be there',
      'will come here',
      'will communicate',
      'will run',
      'will see',
      'will pass',
      'will enable',
      'will strike',
      'will counter-strike'
    ],
    presents: ['saw', 'talks to', 'looks at', 'go to', 'get to know'],
    objects: [
      'them',
      'her',
      'him',
      'the location',
      'the area',
      'it',
      'something',
      'what happened',
      'the object',
      'the thing',
      'the individual',
      'the situation',
      'the process',
      'the story',
      'the screen',
      'the organization',
      'the group',
      'the border',
      'the building',
      'the source',
      'the company',
      'the club',
      'the assembly',
      'the position',
      'someone',
      'black-box',
      'the protocol',
      'the warehouse',
      'the complex',
      'the guard',
      'the hairdresser',
      'the river',
      'the prop',
      'the topography',
      'the space',
      'the weather',
      'the climate',
      'the zone'
    ],
    statements: ['yes', 'no', 'maybe', 'perhaps', 'could be', 'true', 'false', 'sure', 'Now', 'So'],
    questions: ['yes?', 'no?', 'really?', 'why not?', 'how?', 'where?', 'now?', 'why?', 'what?'],
    punctations: ['', '', '', '...', '.'],
    adverbs: [
      'quickly',
      'suddenly',
      'finally',
      'always',
      'never',
      'rarely',
      'really',
      'slowly',
      'carefully',
      'truly',
      'actually',
      'fittingly',
      'quickly',
      'savagely',
      'brutally',
      'calmly',
      'efficiently',
      'extravagantly',
      'in the manner of herding elephants',
      'rigorously',
      'drastically'
    ],
    sentenceTemplates: [
      '{{ statement}}, {{ noun }} {{ verb }} {{ adjective }}',
      '{{ statement}}... {{ noun }} {{ verb }} {{ adjective }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ verb }} {{ adjective }}{{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}',
      '{{ noun }} {{ adverb }} {{ action }} {{ object }}',
      '{{ question }} {{ noun }} {{ action }} {{ object }}?',
      '{{ noun }} {{ verb }} {{ adjective }}?',
      'if {{ noun }} {{ present }} {{ object }}, {{ noun }} {{ future }} {{ punctation }}',
      '{{ noun }} {{ action }} {{ object }}{{ punctation }}'
    ]
  }
}

module.exports = vocabulary
